package bz.sunlight.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Iterator;

public class CallRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table call_record
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table call_record
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table call_record
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public CallRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table call_record
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdIsNull() {
			addCriterion("customer_tag_id is null");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdIsNotNull() {
			addCriterion("customer_tag_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdEqualTo(String value) {
			addCriterion("customer_tag_id =", value, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdNotEqualTo(String value) {
			addCriterion("customer_tag_id <>", value, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdGreaterThan(String value) {
			addCriterion("customer_tag_id >", value, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdGreaterThanOrEqualTo(String value) {
			addCriterion("customer_tag_id >=", value, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdLessThan(String value) {
			addCriterion("customer_tag_id <", value, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdLessThanOrEqualTo(String value) {
			addCriterion("customer_tag_id <=", value, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdLike(String value) {
			addCriterion("customer_tag_id like", value, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdNotLike(String value) {
			addCriterion("customer_tag_id not like", value, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdIn(List<String> values) {
			addCriterion("customer_tag_id in", values, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdNotIn(List<String> values) {
			addCriterion("customer_tag_id not in", values, "customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdBetween(String value1, String value2) {
			addCriterion("customer_tag_id between", value1, value2,
					"customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIdNotBetween(String value1, String value2) {
			addCriterion("customer_tag_id not between", value1, value2,
					"customerTagId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameIsNull() {
			addCriterion("customer_server_nick_name is null");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameIsNotNull() {
			addCriterion("customer_server_nick_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameEqualTo(String value) {
			addCriterion("customer_server_nick_name =", value,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameNotEqualTo(String value) {
			addCriterion("customer_server_nick_name <>", value,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameGreaterThan(String value) {
			addCriterion("customer_server_nick_name >", value,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameGreaterThanOrEqualTo(
				String value) {
			addCriterion("customer_server_nick_name >=", value,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameLessThan(String value) {
			addCriterion("customer_server_nick_name <", value,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameLessThanOrEqualTo(String value) {
			addCriterion("customer_server_nick_name <=", value,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameLike(String value) {
			addCriterion("customer_server_nick_name like", value,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameNotLike(String value) {
			addCriterion("customer_server_nick_name not like", value,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameIn(List<String> values) {
			addCriterion("customer_server_nick_name in", values,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameNotIn(List<String> values) {
			addCriterion("customer_server_nick_name not in", values,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameBetween(String value1,
				String value2) {
			addCriterion("customer_server_nick_name between", value1, value2,
					"customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNickNameNotBetween(String value1,
				String value2) {
			addCriterion("customer_server_nick_name not between", value1,
					value2, "customerServerNickName");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andCallResultIsNull() {
			addCriterion("call_result is null");
			return (Criteria) this;
		}

		public Criteria andCallResultIsNotNull() {
			addCriterion("call_result is not null");
			return (Criteria) this;
		}

		public Criteria andCallResultEqualTo(Short value) {
			addCriterion("call_result =", value, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultNotEqualTo(Short value) {
			addCriterion("call_result <>", value, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultGreaterThan(Short value) {
			addCriterion("call_result >", value, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultGreaterThanOrEqualTo(Short value) {
			addCriterion("call_result >=", value, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultLessThan(Short value) {
			addCriterion("call_result <", value, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultLessThanOrEqualTo(Short value) {
			addCriterion("call_result <=", value, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultIn(List<Short> values) {
			addCriterion("call_result in", values, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultNotIn(List<Short> values) {
			addCriterion("call_result not in", values, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultBetween(Short value1, Short value2) {
			addCriterion("call_result between", value1, value2, "callResult");
			return (Criteria) this;
		}

		public Criteria andCallResultNotBetween(Short value1, Short value2) {
			addCriterion("call_result not between", value1, value2,
					"callResult");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionIsNull() {
			addCriterion("hang_up_position is null");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionIsNotNull() {
			addCriterion("hang_up_position is not null");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionEqualTo(Short value) {
			addCriterion("hang_up_position =", value, "hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionNotEqualTo(Short value) {
			addCriterion("hang_up_position <>", value, "hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionGreaterThan(Short value) {
			addCriterion("hang_up_position >", value, "hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionGreaterThanOrEqualTo(Short value) {
			addCriterion("hang_up_position >=", value, "hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionLessThan(Short value) {
			addCriterion("hang_up_position <", value, "hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionLessThanOrEqualTo(Short value) {
			addCriterion("hang_up_position <=", value, "hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionIn(List<Short> values) {
			addCriterion("hang_up_position in", values, "hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionNotIn(List<Short> values) {
			addCriterion("hang_up_position not in", values, "hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionBetween(Short value1, Short value2) {
			addCriterion("hang_up_position between", value1, value2,
					"hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andHangUpPositionNotBetween(Short value1, Short value2) {
			addCriterion("hang_up_position not between", value1, value2,
					"hangUpPosition");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdIsNull() {
			addCriterion("customer_server_id is null");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdIsNotNull() {
			addCriterion("customer_server_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdEqualTo(String value) {
			addCriterion("customer_server_id =", value, "customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdNotEqualTo(String value) {
			addCriterion("customer_server_id <>", value, "customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdGreaterThan(String value) {
			addCriterion("customer_server_id >", value, "customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdGreaterThanOrEqualTo(String value) {
			addCriterion("customer_server_id >=", value, "customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdLessThan(String value) {
			addCriterion("customer_server_id <", value, "customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdLessThanOrEqualTo(String value) {
			addCriterion("customer_server_id <=", value, "customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdLike(String value) {
			addCriterion("customer_server_id like", value, "customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdNotLike(String value) {
			addCriterion("customer_server_id not like", value,
					"customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdIn(List<String> values) {
			addCriterion("customer_server_id in", values, "customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdNotIn(List<String> values) {
			addCriterion("customer_server_id not in", values,
					"customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdBetween(String value1, String value2) {
			addCriterion("customer_server_id between", value1, value2,
					"customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerIdNotBetween(String value1,
				String value2) {
			addCriterion("customer_server_id not between", value1, value2,
					"customerServerId");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameIsNull() {
			addCriterion("customer_server_name is null");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameIsNotNull() {
			addCriterion("customer_server_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameEqualTo(String value) {
			addCriterion("customer_server_name =", value, "customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameNotEqualTo(String value) {
			addCriterion("customer_server_name <>", value, "customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameGreaterThan(String value) {
			addCriterion("customer_server_name >", value, "customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameGreaterThanOrEqualTo(String value) {
			addCriterion("customer_server_name >=", value, "customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameLessThan(String value) {
			addCriterion("customer_server_name <", value, "customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameLessThanOrEqualTo(String value) {
			addCriterion("customer_server_name <=", value, "customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameLike(String value) {
			addCriterion("customer_server_name like", value,
					"customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameNotLike(String value) {
			addCriterion("customer_server_name not like", value,
					"customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameIn(List<String> values) {
			addCriterion("customer_server_name in", values,
					"customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameNotIn(List<String> values) {
			addCriterion("customer_server_name not in", values,
					"customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameBetween(String value1,
				String value2) {
			addCriterion("customer_server_name between", value1, value2,
					"customerServerName");
			return (Criteria) this;
		}

		public Criteria andCustomerServerNameNotBetween(String value1,
				String value2) {
			addCriterion("customer_server_name not between", value1, value2,
					"customerServerName");
			return (Criteria) this;
		}

		public Criteria andFollowStatusIsNull() {
			addCriterion("follow_status is null");
			return (Criteria) this;
		}

		public Criteria andFollowStatusIsNotNull() {
			addCriterion("follow_status is not null");
			return (Criteria) this;
		}

		public Criteria andFollowStatusEqualTo(Short value) {
			addCriterion("follow_status =", value, "followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusNotEqualTo(Short value) {
			addCriterion("follow_status <>", value, "followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusGreaterThan(Short value) {
			addCriterion("follow_status >", value, "followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("follow_status >=", value, "followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusLessThan(Short value) {
			addCriterion("follow_status <", value, "followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusLessThanOrEqualTo(Short value) {
			addCriterion("follow_status <=", value, "followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusIn(List<Short> values) {
			addCriterion("follow_status in", values, "followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusNotIn(List<Short> values) {
			addCriterion("follow_status not in", values, "followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusBetween(Short value1, Short value2) {
			addCriterion("follow_status between", value1, value2,
					"followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowStatusNotBetween(Short value1, Short value2) {
			addCriterion("follow_status not between", value1, value2,
					"followStatus");
			return (Criteria) this;
		}

		public Criteria andFollowDateIsNull() {
			addCriterion("follow_date is null");
			return (Criteria) this;
		}

		public Criteria andFollowDateIsNotNull() {
			addCriterion("follow_date is not null");
			return (Criteria) this;
		}

		public Criteria andFollowDateEqualTo(Date value) {
			addCriterionForJDBCDate("follow_date =", value, "followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("follow_date <>", value, "followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateGreaterThan(Date value) {
			addCriterionForJDBCDate("follow_date >", value, "followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("follow_date >=", value, "followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateLessThan(Date value) {
			addCriterionForJDBCDate("follow_date <", value, "followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("follow_date <=", value, "followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateIn(List<Date> values) {
			addCriterionForJDBCDate("follow_date in", values, "followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("follow_date not in", values, "followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("follow_date between", value1, value2,
					"followDate");
			return (Criteria) this;
		}

		public Criteria andFollowDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("follow_date not between", value1, value2,
					"followDate");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeIsNull() {
			addCriterion("start_call_time is null");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeIsNotNull() {
			addCriterion("start_call_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeEqualTo(Date value) {
			addCriterion("start_call_time =", value, "startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeNotEqualTo(Date value) {
			addCriterion("start_call_time <>", value, "startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeGreaterThan(Date value) {
			addCriterion("start_call_time >", value, "startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("start_call_time >=", value, "startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeLessThan(Date value) {
			addCriterion("start_call_time <", value, "startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeLessThanOrEqualTo(Date value) {
			addCriterion("start_call_time <=", value, "startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeIn(List<Date> values) {
			addCriterion("start_call_time in", values, "startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeNotIn(List<Date> values) {
			addCriterion("start_call_time not in", values, "startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeBetween(Date value1, Date value2) {
			addCriterion("start_call_time between", value1, value2,
					"startCallTime");
			return (Criteria) this;
		}

		public Criteria andStartCallTimeNotBetween(Date value1, Date value2) {
			addCriterion("start_call_time not between", value1, value2,
					"startCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeIsNull() {
			addCriterion("end_call_time is null");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeIsNotNull() {
			addCriterion("end_call_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeEqualTo(Date value) {
			addCriterion("end_call_time =", value, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeNotEqualTo(Date value) {
			addCriterion("end_call_time <>", value, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeGreaterThan(Date value) {
			addCriterion("end_call_time >", value, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("end_call_time >=", value, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeLessThan(Date value) {
			addCriterion("end_call_time <", value, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeLessThanOrEqualTo(Date value) {
			addCriterion("end_call_time <=", value, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeIn(List<Date> values) {
			addCriterion("end_call_time in", values, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeNotIn(List<Date> values) {
			addCriterion("end_call_time not in", values, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeBetween(Date value1, Date value2) {
			addCriterion("end_call_time between", value1, value2, "endCallTime");
			return (Criteria) this;
		}

		public Criteria andEndCallTimeNotBetween(Date value1, Date value2) {
			addCriterion("end_call_time not between", value1, value2,
					"endCallTime");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileIsNull() {
			addCriterion("virtual_mobile is null");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileIsNotNull() {
			addCriterion("virtual_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileEqualTo(String value) {
			addCriterion("virtual_mobile =", value, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileNotEqualTo(String value) {
			addCriterion("virtual_mobile <>", value, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileGreaterThan(String value) {
			addCriterion("virtual_mobile >", value, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileGreaterThanOrEqualTo(String value) {
			addCriterion("virtual_mobile >=", value, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileLessThan(String value) {
			addCriterion("virtual_mobile <", value, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileLessThanOrEqualTo(String value) {
			addCriterion("virtual_mobile <=", value, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileLike(String value) {
			addCriterion("virtual_mobile like", value, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileNotLike(String value) {
			addCriterion("virtual_mobile not like", value, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileIn(List<String> values) {
			addCriterion("virtual_mobile in", values, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileNotIn(List<String> values) {
			addCriterion("virtual_mobile not in", values, "virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileBetween(String value1, String value2) {
			addCriterion("virtual_mobile between", value1, value2,
					"virtualMobile");
			return (Criteria) this;
		}

		public Criteria andVirtualMobileNotBetween(String value1, String value2) {
			addCriterion("virtual_mobile not between", value1, value2,
					"virtualMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeIsNull() {
			addCriterion("customer_server_code is null");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeIsNotNull() {
			addCriterion("customer_server_code is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeEqualTo(String value) {
			addCriterion("customer_server_code =", value, "customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeNotEqualTo(String value) {
			addCriterion("customer_server_code <>", value, "customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeGreaterThan(String value) {
			addCriterion("customer_server_code >", value, "customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeGreaterThanOrEqualTo(String value) {
			addCriterion("customer_server_code >=", value, "customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeLessThan(String value) {
			addCriterion("customer_server_code <", value, "customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeLessThanOrEqualTo(String value) {
			addCriterion("customer_server_code <=", value, "customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeLike(String value) {
			addCriterion("customer_server_code like", value,
					"customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeNotLike(String value) {
			addCriterion("customer_server_code not like", value,
					"customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeIn(List<String> values) {
			addCriterion("customer_server_code in", values,
					"customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeNotIn(List<String> values) {
			addCriterion("customer_server_code not in", values,
					"customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeBetween(String value1,
				String value2) {
			addCriterion("customer_server_code between", value1, value2,
					"customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerServerCodeNotBetween(String value1,
				String value2) {
			addCriterion("customer_server_code not between", value1, value2,
					"customerServerCode");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIsNull() {
			addCriterion("customer_tag is null");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIsNotNull() {
			addCriterion("customer_tag is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerTagEqualTo(String value) {
			addCriterion("customer_tag =", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagNotEqualTo(String value) {
			addCriterion("customer_tag <>", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagGreaterThan(String value) {
			addCriterion("customer_tag >", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagGreaterThanOrEqualTo(String value) {
			addCriterion("customer_tag >=", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagLessThan(String value) {
			addCriterion("customer_tag <", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagLessThanOrEqualTo(String value) {
			addCriterion("customer_tag <=", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagLike(String value) {
			addCriterion("customer_tag like", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagNotLike(String value) {
			addCriterion("customer_tag not like", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIn(List<String> values) {
			addCriterion("customer_tag in", values, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagNotIn(List<String> values) {
			addCriterion("customer_tag not in", values, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagBetween(String value1, String value2) {
			addCriterion("customer_tag between", value1, value2, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagNotBetween(String value1, String value2) {
			addCriterion("customer_tag not between", value1, value2,
					"customerTag");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(Short value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(Short value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(Short value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Short value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(Short value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(Short value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<Short> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<Short> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(Short value1, Short value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(Short value1, Short value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andImportBatchIsNull() {
			addCriterion("import_batch is null");
			return (Criteria) this;
		}

		public Criteria andImportBatchIsNotNull() {
			addCriterion("import_batch is not null");
			return (Criteria) this;
		}

		public Criteria andImportBatchEqualTo(String value) {
			addCriterion("import_batch =", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchNotEqualTo(String value) {
			addCriterion("import_batch <>", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchGreaterThan(String value) {
			addCriterion("import_batch >", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchGreaterThanOrEqualTo(String value) {
			addCriterion("import_batch >=", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchLessThan(String value) {
			addCriterion("import_batch <", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchLessThanOrEqualTo(String value) {
			addCriterion("import_batch <=", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchLike(String value) {
			addCriterion("import_batch like", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchNotLike(String value) {
			addCriterion("import_batch not like", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchIn(List<String> values) {
			addCriterion("import_batch in", values, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchNotIn(List<String> values) {
			addCriterion("import_batch not in", values, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchBetween(String value1, String value2) {
			addCriterion("import_batch between", value1, value2, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchNotBetween(String value1, String value2) {
			addCriterion("import_batch not between", value1, value2,
					"importBatch");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table call_record
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table call_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}