package bz.sunlight.entity;

import java.util.Date;

public class CallRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.customer_tag_id
	 * @mbggenerated
	 */
	private String customerTagId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.customer_server_nick_name
	 * @mbggenerated
	 */
	private String customerServerNickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.call_result
	 * @mbggenerated
	 */
	private Short callResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.hang_up_position
	 * @mbggenerated
	 */
	private Short hangUpPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.customer_server_id
	 * @mbggenerated
	 */
	private String customerServerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.customer_server_name
	 * @mbggenerated
	 */
	private String customerServerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.follow_status
	 * @mbggenerated
	 */
	private Short followStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.follow_date
	 * @mbggenerated
	 */
	private Date followDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.start_call_time
	 * @mbggenerated
	 */
	private Date startCallTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.end_call_time
	 * @mbggenerated
	 */
	private Date endCallTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.virtual_mobile
	 * @mbggenerated
	 */
	private String virtualMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.customer_server_code
	 * @mbggenerated
	 */
	private String customerServerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.customer_tag
	 * @mbggenerated
	 */
	private String customerTag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.sex
	 * @mbggenerated
	 */
	private Short sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.import_batch
	 * @mbggenerated
	 */
	private String importBatch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.status
	 * @mbggenerated
	 */
	private Short status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.id
	 * @return  the value of call_record.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.id
	 * @param id  the value for call_record.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.customer_tag_id
	 * @return  the value of call_record.customer_tag_id
	 * @mbggenerated
	 */
	public String getCustomerTagId() {
		return customerTagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.customer_tag_id
	 * @param customerTagId  the value for call_record.customer_tag_id
	 * @mbggenerated
	 */
	public void setCustomerTagId(String customerTagId) {
		this.customerTagId = customerTagId == null ? null : customerTagId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.customer_server_nick_name
	 * @return  the value of call_record.customer_server_nick_name
	 * @mbggenerated
	 */
	public String getCustomerServerNickName() {
		return customerServerNickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.customer_server_nick_name
	 * @param customerServerNickName  the value for call_record.customer_server_nick_name
	 * @mbggenerated
	 */
	public void setCustomerServerNickName(String customerServerNickName) {
		this.customerServerNickName = customerServerNickName == null ? null
				: customerServerNickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.create_time
	 * @return  the value of call_record.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.create_time
	 * @param createTime  the value for call_record.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.call_result
	 * @return  the value of call_record.call_result
	 * @mbggenerated
	 */
	public Short getCallResult() {
		return callResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.call_result
	 * @param callResult  the value for call_record.call_result
	 * @mbggenerated
	 */
	public void setCallResult(Short callResult) {
		this.callResult = callResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.remark
	 * @return  the value of call_record.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.remark
	 * @param remark  the value for call_record.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.hang_up_position
	 * @return  the value of call_record.hang_up_position
	 * @mbggenerated
	 */
	public Short getHangUpPosition() {
		return hangUpPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.hang_up_position
	 * @param hangUpPosition  the value for call_record.hang_up_position
	 * @mbggenerated
	 */
	public void setHangUpPosition(Short hangUpPosition) {
		this.hangUpPosition = hangUpPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.customer_server_id
	 * @return  the value of call_record.customer_server_id
	 * @mbggenerated
	 */
	public String getCustomerServerId() {
		return customerServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.customer_server_id
	 * @param customerServerId  the value for call_record.customer_server_id
	 * @mbggenerated
	 */
	public void setCustomerServerId(String customerServerId) {
		this.customerServerId = customerServerId == null ? null
				: customerServerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.customer_server_name
	 * @return  the value of call_record.customer_server_name
	 * @mbggenerated
	 */
	public String getCustomerServerName() {
		return customerServerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.customer_server_name
	 * @param customerServerName  the value for call_record.customer_server_name
	 * @mbggenerated
	 */
	public void setCustomerServerName(String customerServerName) {
		this.customerServerName = customerServerName == null ? null
				: customerServerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.follow_status
	 * @return  the value of call_record.follow_status
	 * @mbggenerated
	 */
	public Short getFollowStatus() {
		return followStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.follow_status
	 * @param followStatus  the value for call_record.follow_status
	 * @mbggenerated
	 */
	public void setFollowStatus(Short followStatus) {
		this.followStatus = followStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.follow_date
	 * @return  the value of call_record.follow_date
	 * @mbggenerated
	 */
	public Date getFollowDate() {
		return followDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.follow_date
	 * @param followDate  the value for call_record.follow_date
	 * @mbggenerated
	 */
	public void setFollowDate(Date followDate) {
		this.followDate = followDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.start_call_time
	 * @return  the value of call_record.start_call_time
	 * @mbggenerated
	 */
	public Date getStartCallTime() {
		return startCallTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.start_call_time
	 * @param startCallTime  the value for call_record.start_call_time
	 * @mbggenerated
	 */
	public void setStartCallTime(Date startCallTime) {
		this.startCallTime = startCallTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.end_call_time
	 * @return  the value of call_record.end_call_time
	 * @mbggenerated
	 */
	public Date getEndCallTime() {
		return endCallTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.end_call_time
	 * @param endCallTime  the value for call_record.end_call_time
	 * @mbggenerated
	 */
	public void setEndCallTime(Date endCallTime) {
		this.endCallTime = endCallTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.virtual_mobile
	 * @return  the value of call_record.virtual_mobile
	 * @mbggenerated
	 */
	public String getVirtualMobile() {
		return virtualMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.virtual_mobile
	 * @param virtualMobile  the value for call_record.virtual_mobile
	 * @mbggenerated
	 */
	public void setVirtualMobile(String virtualMobile) {
		this.virtualMobile = virtualMobile == null ? null : virtualMobile
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.customer_server_code
	 * @return  the value of call_record.customer_server_code
	 * @mbggenerated
	 */
	public String getCustomerServerCode() {
		return customerServerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.customer_server_code
	 * @param customerServerCode  the value for call_record.customer_server_code
	 * @mbggenerated
	 */
	public void setCustomerServerCode(String customerServerCode) {
		this.customerServerCode = customerServerCode == null ? null
				: customerServerCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.customer_tag
	 * @return  the value of call_record.customer_tag
	 * @mbggenerated
	 */
	public String getCustomerTag() {
		return customerTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.customer_tag
	 * @param customerTag  the value for call_record.customer_tag
	 * @mbggenerated
	 */
	public void setCustomerTag(String customerTag) {
		this.customerTag = customerTag == null ? null : customerTag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.name
	 * @return  the value of call_record.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.name
	 * @param name  the value for call_record.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.sex
	 * @return  the value of call_record.sex
	 * @mbggenerated
	 */
	public Short getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.sex
	 * @param sex  the value for call_record.sex
	 * @mbggenerated
	 */
	public void setSex(Short sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.mobile
	 * @return  the value of call_record.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.mobile
	 * @param mobile  the value for call_record.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.import_batch
	 * @return  the value of call_record.import_batch
	 * @mbggenerated
	 */
	public String getImportBatch() {
		return importBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.import_batch
	 * @param importBatch  the value for call_record.import_batch
	 * @mbggenerated
	 */
	public void setImportBatch(String importBatch) {
		this.importBatch = importBatch == null ? null : importBatch.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.status
	 * @return  the value of call_record.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.status
	 * @param status  the value for call_record.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	private CustomerTag customer;

	public CustomerTag getCustomer() {
		return customer;
	}

	public void setCustomer(CustomerTag customer) {
		this.customer = customer;
	}

	private Short followDay;

	public Short getFollowDay() {
		return followDay;
	}

	public void setFollowDay(Short followDay) {
		this.followDay = followDay;
	}
	
	
	
	
	
	
}