package bz.sunlight.entity;

import java.util.Date;

public class CustomerServer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.user_name
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.status
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.nick_name
	 * @mbggenerated
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.code
	 * @mbggenerated
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.enterprise_id
	 * @mbggenerated
	 */
	private String enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.enterprise_code
	 * @mbggenerated
	 */
	private String enterpriseCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_server.enterprise_name
	 * @mbggenerated
	 */
	private String enterpriseName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.id
	 * @return  the value of customer_server.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.id
	 * @param id  the value for customer_server.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.user_name
	 * @return  the value of customer_server.user_name
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.user_name
	 * @param userName  the value for customer_server.user_name
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.password
	 * @return  the value of customer_server.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.password
	 * @param password  the value for customer_server.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.status
	 * @return  the value of customer_server.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.status
	 * @param status  the value for customer_server.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.create_time
	 * @return  the value of customer_server.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.create_time
	 * @param createTime  the value for customer_server.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.nick_name
	 * @return  the value of customer_server.nick_name
	 * @mbggenerated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.nick_name
	 * @param nickName  the value for customer_server.nick_name
	 * @mbggenerated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.name
	 * @return  the value of customer_server.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.name
	 * @param name  the value for customer_server.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.code
	 * @return  the value of customer_server.code
	 * @mbggenerated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.code
	 * @param code  the value for customer_server.code
	 * @mbggenerated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.enterprise_id
	 * @return  the value of customer_server.enterprise_id
	 * @mbggenerated
	 */
	public String getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.enterprise_id
	 * @param enterpriseId  the value for customer_server.enterprise_id
	 * @mbggenerated
	 */
	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.enterprise_code
	 * @return  the value of customer_server.enterprise_code
	 * @mbggenerated
	 */
	public String getEnterpriseCode() {
		return enterpriseCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.enterprise_code
	 * @param enterpriseCode  the value for customer_server.enterprise_code
	 * @mbggenerated
	 */
	public void setEnterpriseCode(String enterpriseCode) {
		this.enterpriseCode = enterpriseCode == null ? null : enterpriseCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_server.enterprise_name
	 * @return  the value of customer_server.enterprise_name
	 * @mbggenerated
	 */
	public String getEnterpriseName() {
		return enterpriseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_server.enterprise_name
	 * @param enterpriseName  the value for customer_server.enterprise_name
	 * @mbggenerated
	 */
	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName == null ? null : enterpriseName
				.trim();
	}
}