package bz.sunlight.entity;

import java.util.Date;

public class CustomerAd {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_ad.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_ad.ad_code
	 * @mbggenerated
	 */
	private String adCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_ad.status
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_ad.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_ad.id
	 * @return  the value of customer_ad.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_ad.id
	 * @param id  the value for customer_ad.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_ad.ad_code
	 * @return  the value of customer_ad.ad_code
	 * @mbggenerated
	 */
	public String getAdCode() {
		return adCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_ad.ad_code
	 * @param adCode  the value for customer_ad.ad_code
	 * @mbggenerated
	 */
	public void setAdCode(String adCode) {
		this.adCode = adCode == null ? null : adCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_ad.status
	 * @return  the value of customer_ad.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_ad.status
	 * @param status  the value for customer_ad.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_ad.create_time
	 * @return  the value of customer_ad.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_ad.create_time
	 * @param createTime  the value for customer_ad.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}