package bz.sunlight.entity;

import java.util.Date;
import java.util.List;

public class CustomerTag {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.customer_ad_id
	 * @mbggenerated
	 */
	private String customerAdId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.customer_tag
	 * @mbggenerated
	 */
	private String customerTag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.import_batch
	 * @mbggenerated
	 */
	private String importBatch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.sex
	 * @mbggenerated
	 */
	private Short sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.status
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.decode_id
	 * @mbggenerated
	 */
	private String decodeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.is_repeate
	 * @mbggenerated
	 */
	private Short isRepeate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.last_operate_time
	 * @mbggenerated
	 */
	private Date lastOperateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.last_customer_server_id
	 * @mbggenerated
	 */
	private String lastCustomerServerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.dial_time
	 * @mbggenerated
	 */
	private Short dialTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.last_customer_server_code
	 * @mbggenerated
	 */
	private String lastCustomerServerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.last_customer_server_name
	 * @mbggenerated
	 */
	private String lastCustomerServerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.last_customer_server_nick_name
	 * @mbggenerated
	 */
	private String lastCustomerServerNickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.enterprise_id
	 * @mbggenerated
	 */
	private String enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.enterprise_code
	 * @mbggenerated
	 */
	private String enterpriseCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_tag.enterprise_name
	 * @mbggenerated
	 */
	private String enterpriseName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.id
	 * @return  the value of customer_tag.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.id
	 * @param id  the value for customer_tag.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.customer_ad_id
	 * @return  the value of customer_tag.customer_ad_id
	 * @mbggenerated
	 */
	public String getCustomerAdId() {
		return customerAdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.customer_ad_id
	 * @param customerAdId  the value for customer_tag.customer_ad_id
	 * @mbggenerated
	 */
	public void setCustomerAdId(String customerAdId) {
		this.customerAdId = customerAdId == null ? null : customerAdId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.customer_tag
	 * @return  the value of customer_tag.customer_tag
	 * @mbggenerated
	 */
	public String getCustomerTag() {
		return customerTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.customer_tag
	 * @param customerTag  the value for customer_tag.customer_tag
	 * @mbggenerated
	 */
	public void setCustomerTag(String customerTag) {
		this.customerTag = customerTag == null ? null : customerTag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.import_batch
	 * @return  the value of customer_tag.import_batch
	 * @mbggenerated
	 */
	public String getImportBatch() {
		return importBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.import_batch
	 * @param importBatch  the value for customer_tag.import_batch
	 * @mbggenerated
	 */
	public void setImportBatch(String importBatch) {
		this.importBatch = importBatch == null ? null : importBatch.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.name
	 * @return  the value of customer_tag.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.name
	 * @param name  the value for customer_tag.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.sex
	 * @return  the value of customer_tag.sex
	 * @mbggenerated
	 */
	public Short getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.sex
	 * @param sex  the value for customer_tag.sex
	 * @mbggenerated
	 */
	public void setSex(Short sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.status
	 * @return  the value of customer_tag.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.status
	 * @param status  the value for customer_tag.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.create_time
	 * @return  the value of customer_tag.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.create_time
	 * @param createTime  the value for customer_tag.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.decode_id
	 * @return  the value of customer_tag.decode_id
	 * @mbggenerated
	 */
	public String getDecodeId() {
		return decodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.decode_id
	 * @param decodeId  the value for customer_tag.decode_id
	 * @mbggenerated
	 */
	public void setDecodeId(String decodeId) {
		this.decodeId = decodeId == null ? null : decodeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.is_repeate
	 * @return  the value of customer_tag.is_repeate
	 * @mbggenerated
	 */
	public Short getIsRepeate() {
		return isRepeate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.is_repeate
	 * @param isRepeate  the value for customer_tag.is_repeate
	 * @mbggenerated
	 */
	public void setIsRepeate(Short isRepeate) {
		this.isRepeate = isRepeate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.last_operate_time
	 * @return  the value of customer_tag.last_operate_time
	 * @mbggenerated
	 */
	public Date getLastOperateTime() {
		return lastOperateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.last_operate_time
	 * @param lastOperateTime  the value for customer_tag.last_operate_time
	 * @mbggenerated
	 */
	public void setLastOperateTime(Date lastOperateTime) {
		this.lastOperateTime = lastOperateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.last_customer_server_id
	 * @return  the value of customer_tag.last_customer_server_id
	 * @mbggenerated
	 */
	public String getLastCustomerServerId() {
		return lastCustomerServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.last_customer_server_id
	 * @param lastCustomerServerId  the value for customer_tag.last_customer_server_id
	 * @mbggenerated
	 */
	public void setLastCustomerServerId(String lastCustomerServerId) {
		this.lastCustomerServerId = lastCustomerServerId == null ? null
				: lastCustomerServerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.dial_time
	 * @return  the value of customer_tag.dial_time
	 * @mbggenerated
	 */
	public Short getDialTime() {
		return dialTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.dial_time
	 * @param dialTime  the value for customer_tag.dial_time
	 * @mbggenerated
	 */
	public void setDialTime(Short dialTime) {
		this.dialTime = dialTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.mobile
	 * @return  the value of customer_tag.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.mobile
	 * @param mobile  the value for customer_tag.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.last_customer_server_code
	 * @return  the value of customer_tag.last_customer_server_code
	 * @mbggenerated
	 */
	public String getLastCustomerServerCode() {
		return lastCustomerServerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.last_customer_server_code
	 * @param lastCustomerServerCode  the value for customer_tag.last_customer_server_code
	 * @mbggenerated
	 */
	public void setLastCustomerServerCode(String lastCustomerServerCode) {
		this.lastCustomerServerCode = lastCustomerServerCode == null ? null
				: lastCustomerServerCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.last_customer_server_name
	 * @return  the value of customer_tag.last_customer_server_name
	 * @mbggenerated
	 */
	public String getLastCustomerServerName() {
		return lastCustomerServerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.last_customer_server_name
	 * @param lastCustomerServerName  the value for customer_tag.last_customer_server_name
	 * @mbggenerated
	 */
	public void setLastCustomerServerName(String lastCustomerServerName) {
		this.lastCustomerServerName = lastCustomerServerName == null ? null
				: lastCustomerServerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.last_customer_server_nick_name
	 * @return  the value of customer_tag.last_customer_server_nick_name
	 * @mbggenerated
	 */
	public String getLastCustomerServerNickName() {
		return lastCustomerServerNickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.last_customer_server_nick_name
	 * @param lastCustomerServerNickName  the value for customer_tag.last_customer_server_nick_name
	 * @mbggenerated
	 */
	public void setLastCustomerServerNickName(String lastCustomerServerNickName) {
		this.lastCustomerServerNickName = lastCustomerServerNickName == null ? null
				: lastCustomerServerNickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.enterprise_id
	 * @return  the value of customer_tag.enterprise_id
	 * @mbggenerated
	 */
	public String getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.enterprise_id
	 * @param enterpriseId  the value for customer_tag.enterprise_id
	 * @mbggenerated
	 */
	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.enterprise_code
	 * @return  the value of customer_tag.enterprise_code
	 * @mbggenerated
	 */
	public String getEnterpriseCode() {
		return enterpriseCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.enterprise_code
	 * @param enterpriseCode  the value for customer_tag.enterprise_code
	 * @mbggenerated
	 */
	public void setEnterpriseCode(String enterpriseCode) {
		this.enterpriseCode = enterpriseCode == null ? null : enterpriseCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_tag.enterprise_name
	 * @return  the value of customer_tag.enterprise_name
	 * @mbggenerated
	 */
	public String getEnterpriseName() {
		return enterpriseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_tag.enterprise_name
	 * @param enterpriseName  the value for customer_tag.enterprise_name
	 * @mbggenerated
	 */
	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName == null ? null : enterpriseName
				.trim();
	}

	private List<CallRecord> callRecords;

	public List<CallRecord> getCallRecords() {
		return callRecords;
	}

	public void setCallRecords(List<CallRecord> callRecords) {
		this.callRecords = callRecords;
	}

	

	

	
    
}