package bz.sunlight.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomerTagExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public CustomerTagExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdIsNull() {
			addCriterion("customer_ad_id is null");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdIsNotNull() {
			addCriterion("customer_ad_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdEqualTo(String value) {
			addCriterion("customer_ad_id =", value, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdNotEqualTo(String value) {
			addCriterion("customer_ad_id <>", value, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdGreaterThan(String value) {
			addCriterion("customer_ad_id >", value, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdGreaterThanOrEqualTo(String value) {
			addCriterion("customer_ad_id >=", value, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdLessThan(String value) {
			addCriterion("customer_ad_id <", value, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdLessThanOrEqualTo(String value) {
			addCriterion("customer_ad_id <=", value, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdLike(String value) {
			addCriterion("customer_ad_id like", value, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdNotLike(String value) {
			addCriterion("customer_ad_id not like", value, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdIn(List<String> values) {
			addCriterion("customer_ad_id in", values, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdNotIn(List<String> values) {
			addCriterion("customer_ad_id not in", values, "customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdBetween(String value1, String value2) {
			addCriterion("customer_ad_id between", value1, value2,
					"customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerAdIdNotBetween(String value1, String value2) {
			addCriterion("customer_ad_id not between", value1, value2,
					"customerAdId");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIsNull() {
			addCriterion("customer_tag is null");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIsNotNull() {
			addCriterion("customer_tag is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerTagEqualTo(String value) {
			addCriterion("customer_tag =", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagNotEqualTo(String value) {
			addCriterion("customer_tag <>", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagGreaterThan(String value) {
			addCriterion("customer_tag >", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagGreaterThanOrEqualTo(String value) {
			addCriterion("customer_tag >=", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagLessThan(String value) {
			addCriterion("customer_tag <", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagLessThanOrEqualTo(String value) {
			addCriterion("customer_tag <=", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagLike(String value) {
			addCriterion("customer_tag like", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagNotLike(String value) {
			addCriterion("customer_tag not like", value, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagIn(List<String> values) {
			addCriterion("customer_tag in", values, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagNotIn(List<String> values) {
			addCriterion("customer_tag not in", values, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagBetween(String value1, String value2) {
			addCriterion("customer_tag between", value1, value2, "customerTag");
			return (Criteria) this;
		}

		public Criteria andCustomerTagNotBetween(String value1, String value2) {
			addCriterion("customer_tag not between", value1, value2,
					"customerTag");
			return (Criteria) this;
		}

		public Criteria andImportBatchIsNull() {
			addCriterion("import_batch is null");
			return (Criteria) this;
		}

		public Criteria andImportBatchIsNotNull() {
			addCriterion("import_batch is not null");
			return (Criteria) this;
		}

		public Criteria andImportBatchEqualTo(String value) {
			addCriterion("import_batch =", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchNotEqualTo(String value) {
			addCriterion("import_batch <>", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchGreaterThan(String value) {
			addCriterion("import_batch >", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchGreaterThanOrEqualTo(String value) {
			addCriterion("import_batch >=", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchLessThan(String value) {
			addCriterion("import_batch <", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchLessThanOrEqualTo(String value) {
			addCriterion("import_batch <=", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchLike(String value) {
			addCriterion("import_batch like", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchNotLike(String value) {
			addCriterion("import_batch not like", value, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchIn(List<String> values) {
			addCriterion("import_batch in", values, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchNotIn(List<String> values) {
			addCriterion("import_batch not in", values, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchBetween(String value1, String value2) {
			addCriterion("import_batch between", value1, value2, "importBatch");
			return (Criteria) this;
		}

		public Criteria andImportBatchNotBetween(String value1, String value2) {
			addCriterion("import_batch not between", value1, value2,
					"importBatch");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(Short value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(Short value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(Short value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Short value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(Short value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(Short value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<Short> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<Short> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(Short value1, Short value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(Short value1, Short value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andDecodeIdIsNull() {
			addCriterion("decode_id is null");
			return (Criteria) this;
		}

		public Criteria andDecodeIdIsNotNull() {
			addCriterion("decode_id is not null");
			return (Criteria) this;
		}

		public Criteria andDecodeIdEqualTo(String value) {
			addCriterion("decode_id =", value, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdNotEqualTo(String value) {
			addCriterion("decode_id <>", value, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdGreaterThan(String value) {
			addCriterion("decode_id >", value, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdGreaterThanOrEqualTo(String value) {
			addCriterion("decode_id >=", value, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdLessThan(String value) {
			addCriterion("decode_id <", value, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdLessThanOrEqualTo(String value) {
			addCriterion("decode_id <=", value, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdLike(String value) {
			addCriterion("decode_id like", value, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdNotLike(String value) {
			addCriterion("decode_id not like", value, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdIn(List<String> values) {
			addCriterion("decode_id in", values, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdNotIn(List<String> values) {
			addCriterion("decode_id not in", values, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdBetween(String value1, String value2) {
			addCriterion("decode_id between", value1, value2, "decodeId");
			return (Criteria) this;
		}

		public Criteria andDecodeIdNotBetween(String value1, String value2) {
			addCriterion("decode_id not between", value1, value2, "decodeId");
			return (Criteria) this;
		}

		public Criteria andIsRepeateIsNull() {
			addCriterion("is_repeate is null");
			return (Criteria) this;
		}

		public Criteria andIsRepeateIsNotNull() {
			addCriterion("is_repeate is not null");
			return (Criteria) this;
		}

		public Criteria andIsRepeateEqualTo(Short value) {
			addCriterion("is_repeate =", value, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateNotEqualTo(Short value) {
			addCriterion("is_repeate <>", value, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateGreaterThan(Short value) {
			addCriterion("is_repeate >", value, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateGreaterThanOrEqualTo(Short value) {
			addCriterion("is_repeate >=", value, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateLessThan(Short value) {
			addCriterion("is_repeate <", value, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateLessThanOrEqualTo(Short value) {
			addCriterion("is_repeate <=", value, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateIn(List<Short> values) {
			addCriterion("is_repeate in", values, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateNotIn(List<Short> values) {
			addCriterion("is_repeate not in", values, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateBetween(Short value1, Short value2) {
			addCriterion("is_repeate between", value1, value2, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andIsRepeateNotBetween(Short value1, Short value2) {
			addCriterion("is_repeate not between", value1, value2, "isRepeate");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeIsNull() {
			addCriterion("last_operate_time is null");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeIsNotNull() {
			addCriterion("last_operate_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeEqualTo(Date value) {
			addCriterion("last_operate_time =", value, "lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeNotEqualTo(Date value) {
			addCriterion("last_operate_time <>", value, "lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeGreaterThan(Date value) {
			addCriterion("last_operate_time >", value, "lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("last_operate_time >=", value, "lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeLessThan(Date value) {
			addCriterion("last_operate_time <", value, "lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeLessThanOrEqualTo(Date value) {
			addCriterion("last_operate_time <=", value, "lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeIn(List<Date> values) {
			addCriterion("last_operate_time in", values, "lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeNotIn(List<Date> values) {
			addCriterion("last_operate_time not in", values, "lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeBetween(Date value1, Date value2) {
			addCriterion("last_operate_time between", value1, value2,
					"lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastOperateTimeNotBetween(Date value1, Date value2) {
			addCriterion("last_operate_time not between", value1, value2,
					"lastOperateTime");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdIsNull() {
			addCriterion("last_customer_server_id is null");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdIsNotNull() {
			addCriterion("last_customer_server_id is not null");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdEqualTo(String value) {
			addCriterion("last_customer_server_id =", value,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdNotEqualTo(String value) {
			addCriterion("last_customer_server_id <>", value,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdGreaterThan(String value) {
			addCriterion("last_customer_server_id >", value,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdGreaterThanOrEqualTo(String value) {
			addCriterion("last_customer_server_id >=", value,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdLessThan(String value) {
			addCriterion("last_customer_server_id <", value,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdLessThanOrEqualTo(String value) {
			addCriterion("last_customer_server_id <=", value,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdLike(String value) {
			addCriterion("last_customer_server_id like", value,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdNotLike(String value) {
			addCriterion("last_customer_server_id not like", value,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdIn(List<String> values) {
			addCriterion("last_customer_server_id in", values,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdNotIn(List<String> values) {
			addCriterion("last_customer_server_id not in", values,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdBetween(String value1,
				String value2) {
			addCriterion("last_customer_server_id between", value1, value2,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerIdNotBetween(String value1,
				String value2) {
			addCriterion("last_customer_server_id not between", value1, value2,
					"lastCustomerServerId");
			return (Criteria) this;
		}

		public Criteria andDialTimeIsNull() {
			addCriterion("dial_time is null");
			return (Criteria) this;
		}

		public Criteria andDialTimeIsNotNull() {
			addCriterion("dial_time is not null");
			return (Criteria) this;
		}

		public Criteria andDialTimeEqualTo(Short value) {
			addCriterion("dial_time =", value, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeNotEqualTo(Short value) {
			addCriterion("dial_time <>", value, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeGreaterThan(Short value) {
			addCriterion("dial_time >", value, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeGreaterThanOrEqualTo(Short value) {
			addCriterion("dial_time >=", value, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeLessThan(Short value) {
			addCriterion("dial_time <", value, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeLessThanOrEqualTo(Short value) {
			addCriterion("dial_time <=", value, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeIn(List<Short> values) {
			addCriterion("dial_time in", values, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeNotIn(List<Short> values) {
			addCriterion("dial_time not in", values, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeBetween(Short value1, Short value2) {
			addCriterion("dial_time between", value1, value2, "dialTime");
			return (Criteria) this;
		}

		public Criteria andDialTimeNotBetween(Short value1, Short value2) {
			addCriterion("dial_time not between", value1, value2, "dialTime");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeIsNull() {
			addCriterion("last_customer_server_code is null");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeIsNotNull() {
			addCriterion("last_customer_server_code is not null");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeEqualTo(String value) {
			addCriterion("last_customer_server_code =", value,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeNotEqualTo(String value) {
			addCriterion("last_customer_server_code <>", value,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeGreaterThan(String value) {
			addCriterion("last_customer_server_code >", value,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeGreaterThanOrEqualTo(
				String value) {
			addCriterion("last_customer_server_code >=", value,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeLessThan(String value) {
			addCriterion("last_customer_server_code <", value,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeLessThanOrEqualTo(String value) {
			addCriterion("last_customer_server_code <=", value,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeLike(String value) {
			addCriterion("last_customer_server_code like", value,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeNotLike(String value) {
			addCriterion("last_customer_server_code not like", value,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeIn(List<String> values) {
			addCriterion("last_customer_server_code in", values,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeNotIn(List<String> values) {
			addCriterion("last_customer_server_code not in", values,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeBetween(String value1,
				String value2) {
			addCriterion("last_customer_server_code between", value1, value2,
					"lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerCodeNotBetween(String value1,
				String value2) {
			addCriterion("last_customer_server_code not between", value1,
					value2, "lastCustomerServerCode");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameIsNull() {
			addCriterion("last_customer_server_name is null");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameIsNotNull() {
			addCriterion("last_customer_server_name is not null");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameEqualTo(String value) {
			addCriterion("last_customer_server_name =", value,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameNotEqualTo(String value) {
			addCriterion("last_customer_server_name <>", value,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameGreaterThan(String value) {
			addCriterion("last_customer_server_name >", value,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameGreaterThanOrEqualTo(
				String value) {
			addCriterion("last_customer_server_name >=", value,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameLessThan(String value) {
			addCriterion("last_customer_server_name <", value,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameLessThanOrEqualTo(String value) {
			addCriterion("last_customer_server_name <=", value,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameLike(String value) {
			addCriterion("last_customer_server_name like", value,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameNotLike(String value) {
			addCriterion("last_customer_server_name not like", value,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameIn(List<String> values) {
			addCriterion("last_customer_server_name in", values,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameNotIn(List<String> values) {
			addCriterion("last_customer_server_name not in", values,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameBetween(String value1,
				String value2) {
			addCriterion("last_customer_server_name between", value1, value2,
					"lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNameNotBetween(String value1,
				String value2) {
			addCriterion("last_customer_server_name not between", value1,
					value2, "lastCustomerServerName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameIsNull() {
			addCriterion("last_customer_server_nick_name is null");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameIsNotNull() {
			addCriterion("last_customer_server_nick_name is not null");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameEqualTo(String value) {
			addCriterion("last_customer_server_nick_name =", value,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameNotEqualTo(String value) {
			addCriterion("last_customer_server_nick_name <>", value,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameGreaterThan(String value) {
			addCriterion("last_customer_server_nick_name >", value,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameGreaterThanOrEqualTo(
				String value) {
			addCriterion("last_customer_server_nick_name >=", value,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameLessThan(String value) {
			addCriterion("last_customer_server_nick_name <", value,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameLessThanOrEqualTo(
				String value) {
			addCriterion("last_customer_server_nick_name <=", value,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameLike(String value) {
			addCriterion("last_customer_server_nick_name like", value,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameNotLike(String value) {
			addCriterion("last_customer_server_nick_name not like", value,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameIn(List<String> values) {
			addCriterion("last_customer_server_nick_name in", values,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameNotIn(List<String> values) {
			addCriterion("last_customer_server_nick_name not in", values,
					"lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameBetween(String value1,
				String value2) {
			addCriterion("last_customer_server_nick_name between", value1,
					value2, "lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andLastCustomerServerNickNameNotBetween(String value1,
				String value2) {
			addCriterion("last_customer_server_nick_name not between", value1,
					value2, "lastCustomerServerNickName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdIsNull() {
			addCriterion("enterprise_id is null");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdIsNotNull() {
			addCriterion("enterprise_id is not null");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdEqualTo(String value) {
			addCriterion("enterprise_id =", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdNotEqualTo(String value) {
			addCriterion("enterprise_id <>", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdGreaterThan(String value) {
			addCriterion("enterprise_id >", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdGreaterThanOrEqualTo(String value) {
			addCriterion("enterprise_id >=", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdLessThan(String value) {
			addCriterion("enterprise_id <", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdLessThanOrEqualTo(String value) {
			addCriterion("enterprise_id <=", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdLike(String value) {
			addCriterion("enterprise_id like", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdNotLike(String value) {
			addCriterion("enterprise_id not like", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdIn(List<String> values) {
			addCriterion("enterprise_id in", values, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdNotIn(List<String> values) {
			addCriterion("enterprise_id not in", values, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdBetween(String value1, String value2) {
			addCriterion("enterprise_id between", value1, value2,
					"enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdNotBetween(String value1, String value2) {
			addCriterion("enterprise_id not between", value1, value2,
					"enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeIsNull() {
			addCriterion("enterprise_code is null");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeIsNotNull() {
			addCriterion("enterprise_code is not null");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeEqualTo(String value) {
			addCriterion("enterprise_code =", value, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeNotEqualTo(String value) {
			addCriterion("enterprise_code <>", value, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeGreaterThan(String value) {
			addCriterion("enterprise_code >", value, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeGreaterThanOrEqualTo(String value) {
			addCriterion("enterprise_code >=", value, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeLessThan(String value) {
			addCriterion("enterprise_code <", value, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeLessThanOrEqualTo(String value) {
			addCriterion("enterprise_code <=", value, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeLike(String value) {
			addCriterion("enterprise_code like", value, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeNotLike(String value) {
			addCriterion("enterprise_code not like", value, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeIn(List<String> values) {
			addCriterion("enterprise_code in", values, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeNotIn(List<String> values) {
			addCriterion("enterprise_code not in", values, "enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeBetween(String value1, String value2) {
			addCriterion("enterprise_code between", value1, value2,
					"enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseCodeNotBetween(String value1, String value2) {
			addCriterion("enterprise_code not between", value1, value2,
					"enterpriseCode");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameIsNull() {
			addCriterion("enterprise_name is null");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameIsNotNull() {
			addCriterion("enterprise_name is not null");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameEqualTo(String value) {
			addCriterion("enterprise_name =", value, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameNotEqualTo(String value) {
			addCriterion("enterprise_name <>", value, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameGreaterThan(String value) {
			addCriterion("enterprise_name >", value, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameGreaterThanOrEqualTo(String value) {
			addCriterion("enterprise_name >=", value, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameLessThan(String value) {
			addCriterion("enterprise_name <", value, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameLessThanOrEqualTo(String value) {
			addCriterion("enterprise_name <=", value, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameLike(String value) {
			addCriterion("enterprise_name like", value, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameNotLike(String value) {
			addCriterion("enterprise_name not like", value, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameIn(List<String> values) {
			addCriterion("enterprise_name in", values, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameNotIn(List<String> values) {
			addCriterion("enterprise_name not in", values, "enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameBetween(String value1, String value2) {
			addCriterion("enterprise_name between", value1, value2,
					"enterpriseName");
			return (Criteria) this;
		}

		public Criteria andEnterpriseNameNotBetween(String value1, String value2) {
			addCriterion("enterprise_name not between", value1, value2,
					"enterpriseName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_tag
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}