package bz.sunlight.entity;

import java.util.Date;

public class KeyValueItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_item.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_item.key_value_categoty_id
	 * @mbggenerated
	 */
	private String keyValueCategotyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_item.code
	 * @mbggenerated
	 */
	private Short code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_item.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_item.status
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_item.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_item.create_person
	 * @mbggenerated
	 */
	private String createPerson;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_item.id
	 * @return  the value of key_value_item.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_item.id
	 * @param id  the value for key_value_item.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_item.key_value_categoty_id
	 * @return  the value of key_value_item.key_value_categoty_id
	 * @mbggenerated
	 */
	public String getKeyValueCategotyId() {
		return keyValueCategotyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_item.key_value_categoty_id
	 * @param keyValueCategotyId  the value for key_value_item.key_value_categoty_id
	 * @mbggenerated
	 */
	public void setKeyValueCategotyId(String keyValueCategotyId) {
		this.keyValueCategotyId = keyValueCategotyId == null ? null
				: keyValueCategotyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_item.code
	 * @return  the value of key_value_item.code
	 * @mbggenerated
	 */
	public Short getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_item.code
	 * @param code  the value for key_value_item.code
	 * @mbggenerated
	 */
	public void setCode(Short code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_item.name
	 * @return  the value of key_value_item.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_item.name
	 * @param name  the value for key_value_item.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_item.status
	 * @return  the value of key_value_item.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_item.status
	 * @param status  the value for key_value_item.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_item.create_time
	 * @return  the value of key_value_item.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_item.create_time
	 * @param createTime  the value for key_value_item.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_item.create_person
	 * @return  the value of key_value_item.create_person
	 * @mbggenerated
	 */
	public String getCreatePerson() {
		return createPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_item.create_person
	 * @param createPerson  the value for key_value_item.create_person
	 * @mbggenerated
	 */
	public void setCreatePerson(String createPerson) {
		this.createPerson = createPerson == null ? null : createPerson.trim();
	}
}