package bz.sunlight.entity;

import java.util.Date;
import java.util.List;

public class KeyValueCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_category.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_category.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_category.code
	 * @mbggenerated
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_category.status
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_category.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column key_value_category.is_admin_build
	 * @mbggenerated
	 */
	private Short isAdminBuild;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_category.id
	 * @return  the value of key_value_category.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_category.id
	 * @param id  the value for key_value_category.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_category.name
	 * @return  the value of key_value_category.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_category.name
	 * @param name  the value for key_value_category.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_category.code
	 * @return  the value of key_value_category.code
	 * @mbggenerated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_category.code
	 * @param code  the value for key_value_category.code
	 * @mbggenerated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_category.status
	 * @return  the value of key_value_category.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_category.status
	 * @param status  the value for key_value_category.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_category.create_time
	 * @return  the value of key_value_category.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_category.create_time
	 * @param createTime  the value for key_value_category.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column key_value_category.is_admin_build
	 * @return  the value of key_value_category.is_admin_build
	 * @mbggenerated
	 */
	public Short getIsAdminBuild() {
		return isAdminBuild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column key_value_category.is_admin_build
	 * @param isAdminBuild  the value for key_value_category.is_admin_build
	 * @mbggenerated
	 */
	public void setIsAdminBuild(Short isAdminBuild) {
		this.isAdminBuild = isAdminBuild;
	}

	private List<KeyValueItem> keyValueItems;

	public List<KeyValueItem> getKeyValueItems() {
		return keyValueItems;
	}

	public void setKeyValueItems(List<KeyValueItem> keyValueItems) {
		this.keyValueItems = keyValueItems;
	}
	
	
}