package bz.sunlight.dao;

import bz.sunlight.entity.CallRecord;
import bz.sunlight.entity.CallRecordExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CallRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int countByExample(CallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int deleteByExample(CallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int insert(CallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int insertSelective(CallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	List<CallRecord> selectByExample(CallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	CallRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") CallRecord record,
			@Param("example") CallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CallRecord record,
			@Param("example") CallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CallRecord record);

	int selectRecordCount(Map map);
	
	List<CallRecord> selectRecordByBatch(Map map);

	List<CallRecord> getCallRecordByCustomerTagId(String customerTagId);
	
	List<CallRecord> getCallRecordByCustomerTagIdExcel(Map map);
	
	void updateByIdSelective(CallRecord record);
	
	
}