package bz.sunlight.dao;

import bz.sunlight.dto.CallRecordDTO;
import bz.sunlight.entity.CustomerTag;
import bz.sunlight.entity.CustomerTagExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CustomerTagMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int countByExample(CustomerTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int deleteByExample(CustomerTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int insert(CustomerTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int insertSelective(CustomerTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	List<CustomerTag> selectByExample(CustomerTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	CustomerTag selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") CustomerTag record,
			@Param("example") CustomerTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CustomerTag record,
			@Param("example") CustomerTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CustomerTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_tag
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerTag record);

	List<CustomerTag> selectByPage(Map<String,Object> map);
	
	List<CustomerTag> selectCustomerTagByPage(Map<String,Object> map);
    
    List<String> selectionBatch();
    
    int getCount(String batch);
    
    List<CustomerTag> selectCustomerTagByCondition(CallRecordDTO callRecordDTO);
    
    int selectCustomerTagCountByCondition(CallRecordDTO callRecordDTO);
    
    List<CustomerTag> selectCustomerTagByConditionExcel(CallRecordDTO callRecordDTO);
    
    List<CustomerTag> selectCustomerTagByConditionTest(CallRecordDTO callRecordDTO);
}