package bz.sunlight.dao;

import bz.sunlight.entity.CustomerServer;
import bz.sunlight.entity.CustomerServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerServerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int countByExample(CustomerServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int deleteByExample(CustomerServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int insert(CustomerServer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int insertSelective(CustomerServer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	List<CustomerServer> selectByExample(CustomerServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	CustomerServer selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") CustomerServer record,
			@Param("example") CustomerServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CustomerServer record,
			@Param("example") CustomerServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CustomerServer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_server
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerServer record);
}